# Cartesian Product with Python Libraries

----

Author: [**Mirko M. Stojiljković**, Ph.D.](http://mmst.tech)

Version: **1.0**

Last updated: **04 April 2020**

License: [**MIT**](https://opensource.org/licenses/MIT)

----

Copyright 2020 Mirko Stojiljković

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

----

## Cartesian Product

The [**Cartesian product**](https://en.wikipedia.org/wiki/Cartesian_product) of $n$ sets $X_1$, $X_2$, $\ldots$, $X_n$ is the set of all possible ordered tuples ($x_1, x_2, \ldots, x_n$), where $x_1$, $x_2$, $\ldots$, $x_n$ are the elements such that $x_1 \in X_1$, $x_2 \in X_2$, $\ldots$, $x_n \in X_n$.

For example, if we have three sets:

$$
X = \{ 0, 1 \} \\
Y = \{ a, b, c \} \\
Z = \{ t, f \}
$$

their Cartesian product is:

$$
X \times Y \times Z =
  \{
     (0, a, t), (0, a, f), (0, b, t), (0, b, f), (0, c, t), (0, c, f),
     (1, a, t), (1, a, f), (1, b, t), (1, b, f), (1, c, t), (1, c, f)
  \}
$$

Python offers several ways to get the Cartesian product given the sets (or tuples or lists or other sequences) of input values.

## Cartesian Product with itertools

The built-in Python library [itertools](https://docs.python.org/3.8/library/itertools.html) has the iterator [`product`](https://docs.python.org/3.8/library/itertools.html#itertools.product) that you can use to calculate the Cartesian product.

Let's solve the problem above with `product`.

In [22]:
from itertools import product

x = {0, 1}
y = ('a', 'b', 'c')
z = [True, False]

prod = product(x, y, z)

In [23]:
prod

The inputs can be sets, tuples, lists, or other Python sequences. Even [`range`](https://docs.python.org/3/library/functions.html#func-range) or string. For example, we would get the same result with `x = range(2)` and `y = 'abc'`.

By applying `product` you get the object that is an iterable and iterator:

In [24]:
hasattr(prod, '__iter__'), hasattr(prod, '__next__'),

(True, True)

This means that you can use it in a `for` loop or get a set or tuple or list from it:

In [25]:
for item in product(x, y, z):
    print(item)

(0, 'a', True)
(0, 'a', False)
(0, 'b', True)
(0, 'b', False)
(0, 'c', True)
(0, 'c', False)
(1, 'a', True)
(1, 'a', False)
(1, 'b', True)
(1, 'b', False)
(1, 'c', True)
(1, 'c', False)


In [8]:
set(product(x, y, z))

{(0, 'a', False),
 (0, 'a', True),
 (0, 'b', False),
 (0, 'b', True),
 (0, 'c', False),
 (0, 'c', True),
 (1, 'a', False),
 (1, 'a', True),
 (1, 'b', False),
 (1, 'b', True),
 (1, 'c', False),
 (1, 'c', True)}

In [9]:
tuple(product(x, y, z))

((0, 'a', True),
 (0, 'a', False),
 (0, 'b', True),
 (0, 'b', False),
 (0, 'c', True),
 (0, 'c', False),
 (1, 'a', True),
 (1, 'a', False),
 (1, 'b', True),
 (1, 'b', False),
 (1, 'c', True),
 (1, 'c', False))

In [10]:
list(product(x, y, z))

[(0, 'a', True),
 (0, 'a', False),
 (0, 'b', True),
 (0, 'b', False),
 (0, 'c', True),
 (0, 'c', False),
 (1, 'a', True),
 (1, 'a', False),
 (1, 'b', True),
 (1, 'b', False),
 (1, 'c', True),
 (1, 'c', False)]

We now have the set, tuple, and list that hold the Cartesian product of `x`, `y`, and `z`.

## Cartesian Product with NumPy (Part 1 of 2)

You can get the Cartesian product with NumPy by combining several functions:

In [26]:
import numpy as np

x, y, z = np.arange(2), np.array(tuple('abc')), np.array([True, False])

prod = np.stack(np.meshgrid(x, y, z, indexing='ij'), axis=-1).reshape(-1, 3)

prod

array([['0', 'a', 'True'],
       ['0', 'a', 'False'],
       ['0', 'b', 'True'],
       ['0', 'b', 'False'],
       ['0', 'c', 'True'],
       ['0', 'c', 'False'],
       ['1', 'a', 'True'],
       ['1', 'a', 'False'],
       ['1', 'b', 'True'],
       ['1', 'b', 'False'],
       ['1', 'c', 'True'],
       ['1', 'c', 'False']], dtype='<U21')

Here it is. We used:

* [`meshgrid()`](https://numpy.org/doc/1.18/reference/generated/numpy.meshgrid.html) to get the arrays with repeated elements to be combined
* [`stack()`](https://numpy.org/doc/1.18/reference/generated/numpy.stack.html) to join these arrays into a single resulting array
* [`.reshape()`](https://numpy.org/doc/1.18/reference/generated/numpy.ndarray.reshape.html#numpy.ndarray.reshape) or [`reshape()`](https://numpy.org/doc/1.18/reference/generated/numpy.reshape.html) to make the resulting array two-dimensional

Let's see what's going on in each step:

In [27]:
np.meshgrid(x, y, z, indexing='ij')

[array([[[0, 0],
         [0, 0],
         [0, 0]],
 
        [[1, 1],
         [1, 1],
         [1, 1]]]),
 array([[['a', 'a'],
         ['b', 'b'],
         ['c', 'c']],
 
        [['a', 'a'],
         ['b', 'b'],
         ['c', 'c']]], dtype='<U1'),
 array([[[ True, False],
         [ True, False],
         [ True, False]],
 
        [[ True, False],
         [ True, False],
         [ True, False]]])]

In [28]:
np.stack(np.meshgrid(x, y, z, indexing='ij'), axis=-1)

array([[[['0', 'a', 'True'],
         ['0', 'a', 'False']],

        [['0', 'b', 'True'],
         ['0', 'b', 'False']],

        [['0', 'c', 'True'],
         ['0', 'c', 'False']]],


       [[['1', 'a', 'True'],
         ['1', 'a', 'False']],

        [['1', 'b', 'True'],
         ['1', 'b', 'False']],

        [['1', 'c', 'True'],
         ['1', 'c', 'False']]]], dtype='<U21')

In [29]:
np.stack(np.meshgrid(x, y, z, indexing='ij'), axis=-1).reshape(-1, 3)

array([['0', 'a', 'True'],
       ['0', 'a', 'False'],
       ['0', 'b', 'True'],
       ['0', 'b', 'False'],
       ['0', 'c', 'True'],
       ['0', 'c', 'False'],
       ['1', 'a', 'True'],
       ['1', 'a', 'False'],
       ['1', 'b', 'True'],
       ['1', 'b', 'False'],
       ['1', 'c', 'True'],
       ['1', 'c', 'False']], dtype='<U21')

All elements from a NumPy array must have the same type. When we combine several arrays of different types (here with `stack()`), NumPy chooses the most general type for the resulting array. This is why the elements of the Cartesian product are strings.

## Cartesian Product with NumPy (Part 2 of 2)

If we have NumPy arrays that represent regular grids, we can do this another way:

In [42]:
import numpy as np

x, y, z = np.s_[1:5], np.s_[:5:2], np.s_[:2]

prod = np.mgrid[x, y, z].transpose((1, 2, 3, 0)).reshape(-1, 3)

prod

array([[1, 0, 0],
       [1, 0, 1],
       [1, 2, 0],
       [1, 2, 1],
       [1, 4, 0],
       [1, 4, 1],
       [2, 0, 0],
       [2, 0, 1],
       [2, 2, 0],
       [2, 2, 1],
       [2, 4, 0],
       [2, 4, 1],
       [3, 0, 0],
       [3, 0, 1],
       [3, 2, 0],
       [3, 2, 1],
       [3, 4, 0],
       [3, 4, 1],
       [4, 0, 0],
       [4, 0, 1],
       [4, 2, 0],
       [4, 2, 1],
       [4, 4, 0],
       [4, 4, 1]])

First, we use [`s_`](https://numpy.org/doc/1.18/reference/generated/numpy.s_.html) to create the slices that represent the regular grid. We can use the built-in [`slice`](https://docs.python.org/3/library/functions.html#slice) as well.

In [41]:
x, y, z

(slice(1, 5, None), slice(None, 5, 2), slice(None, 2, None))

Next we combine:

* [`meshgrid`](https://numpy.org/doc/1.18/reference/generated/numpy.mgrid.html) to get the array that represents the regular grid
* [`.transpose()`](https://numpy.org/doc/1.18/reference/generated/numpy.ndarray.transpose.html), [`transpose`](https://numpy.org/doc/1.18/reference/generated/numpy.transpose.html), or [`.T`](https://numpy.org/doc/1.18/reference/generated/numpy.ndarray.T.html) (in simpler cases) to change the order of axes for the obtained array
* [`.reshape()`](https://numpy.org/doc/1.18/reference/generated/numpy.ndarray.reshape.html#numpy.ndarray.reshape) or [`reshape()`](https://numpy.org/doc/1.18/reference/generated/numpy.reshape.html) to make the resulting array two-dimensional

Let's see what's going on in each step:

In [43]:
np.mgrid[x, y, z]

array([[[[1, 1],
         [1, 1],
         [1, 1]],

        [[2, 2],
         [2, 2],
         [2, 2]],

        [[3, 3],
         [3, 3],
         [3, 3]],

        [[4, 4],
         [4, 4],
         [4, 4]]],


       [[[0, 0],
         [2, 2],
         [4, 4]],

        [[0, 0],
         [2, 2],
         [4, 4]],

        [[0, 0],
         [2, 2],
         [4, 4]],

        [[0, 0],
         [2, 2],
         [4, 4]]],


       [[[0, 1],
         [0, 1],
         [0, 1]],

        [[0, 1],
         [0, 1],
         [0, 1]],

        [[0, 1],
         [0, 1],
         [0, 1]],

        [[0, 1],
         [0, 1],
         [0, 1]]]])

In [44]:
np.mgrid[x, y, z].transpose((1, 2, 3, 0))

array([[[[1, 0, 0],
         [1, 0, 1]],

        [[1, 2, 0],
         [1, 2, 1]],

        [[1, 4, 0],
         [1, 4, 1]]],


       [[[2, 0, 0],
         [2, 0, 1]],

        [[2, 2, 0],
         [2, 2, 1]],

        [[2, 4, 0],
         [2, 4, 1]]],


       [[[3, 0, 0],
         [3, 0, 1]],

        [[3, 2, 0],
         [3, 2, 1]],

        [[3, 4, 0],
         [3, 4, 1]]],


       [[[4, 0, 0],
         [4, 0, 1]],

        [[4, 2, 0],
         [4, 2, 1]],

        [[4, 4, 0],
         [4, 4, 1]]]])

In [45]:
np.mgrid[x, y, z].transpose((1, 2, 3, 0)).reshape(-1, 3)

array([[1, 0, 0],
       [1, 0, 1],
       [1, 2, 0],
       [1, 2, 1],
       [1, 4, 0],
       [1, 4, 1],
       [2, 0, 0],
       [2, 0, 1],
       [2, 2, 0],
       [2, 2, 1],
       [2, 4, 0],
       [2, 4, 1],
       [3, 0, 0],
       [3, 0, 1],
       [3, 2, 0],
       [3, 2, 1],
       [3, 4, 0],
       [3, 4, 1],
       [4, 0, 0],
       [4, 0, 1],
       [4, 2, 0],
       [4, 2, 1],
       [4, 4, 0],
       [4, 4, 1]])

Again, we got the array that represents the Cartesian product. This time, it has integer elements.

## Concusion

This notebook offers three solutions to easily calculate the Cartesian product in Python. One of them uses the built-in itertools library and the other two apply NumPy.

----

Author: [**Mirko M. Stojiljković**, Ph.D.](http://mmst.tech) [@MMStojiljkovic](https://twitter.com/MMStojiljkovic)